import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./components/Megamenu";
import { PageFooter } from "./components/Foot";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <nav className="w-full p-1">
          <Nav />
        </nav>
        <div className="bg-slate-200 w-full flex-grow">{children}</div>
        <PageFooter />
      </body>
    </html>
  );
}
